# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab7dca42bedd8022dc86b8419b7003b5"
application_url = "https://casinos-essay-viii-vegetable.trycloudflare.com"
embedded = true
name = "wishfull-app"
handle = "wishfull-app"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, customer_write_customers, read_customers"

[auth]
redirect_urls = ["https://casinos-essay-viii-vegetable.trycloudflare.com/auth/callback", "https://casinos-essay-viii-vegetable.trycloudflare.com/auth/shopify/callback", "https://casinos-essay-viii-vegetable.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "palnice.myshopify.com"
include_config_on_deploy = true
